# Generated by Django 3.0 on 2020-02-02 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_Professor',
            new_name='is_professor',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_Administrative',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_TA',
        ),
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.CharField(default='none', max_length=255),
            preserve_default=False,
        ),
    ]
