# Generated by Django 3.0 on 2020-02-03 01:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reservation', '0003_auto_20200203_0107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='approver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_req', to=settings.AUTH_USER_MODEL),
        ),
    ]
