# Generated by Django 3.0 on 2020-02-02 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('rooms', '0002_auto_20200202_2100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='department',
        ),
        migrations.CreateModel(
            name='RoomGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('approve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rg_approves', to='auth.Permission')),
                ('own', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rg_owns', to='auth.Permission')),
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='group',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='rooms.RoomGroup'),
            preserve_default=False,
        ),
    ]
