# Generated by Django 3.0 on 2020-02-02 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_auto_20200202_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='type',
            field=models.CharField(default='class', max_length=128),
            preserve_default=False,
        ),
    ]
